// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"time"

	"github.com/sxwebdev/donejournal/internal/store/storecmn"
)

type Inbox struct {
	ID             string             `db:"id" json:"id" validate:"required"`
	Data           string             `db:"data" json:"data" validate:"required"`
	AdditionalData storecmn.JSONField `db:"additional_data" json:"additional_data"`
	UserID         string             `db:"user_id" json:"user_id" validate:"required"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time          `db:"updated_at" json:"updated_at"`
}

type Todo struct {
	ID          string         `db:"id" json:"id" validate:"required"`
	UserID      string         `db:"user_id" json:"user_id" validate:"required"`
	Title       string         `db:"title" json:"title" validate:"required"`
	Description string         `db:"description" json:"description"`
	Status      TodoStatusType `db:"status" json:"status" validate:"required,oneof=pending inprogress completed cancelled"`
	PlannedDate time.Time      `db:"planned_date" json:"planned_date"`
	CompletedAt *time.Time     `db:"completed_at" json:"completed_at"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}
