// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.13
package repo_requests

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameRequests TableName = "requests"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameRequestsId           ColumnName = "id"
	ColumnNameRequestsData         ColumnName = "data"
	ColumnNameRequestsStatus       ColumnName = "status"
	ColumnNameRequestsErrorMessage ColumnName = "error_message"
	ColumnNameRequestsUserId       ColumnName = "user_id"
	ColumnNameRequestsCreatedAt    ColumnName = "created_at"
	ColumnNameRequestsUpdatedAt    ColumnName = "updated_at"
)

func RequestsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameRequestsId,
		ColumnNameRequestsData,
		ColumnNameRequestsStatus,
		ColumnNameRequestsErrorMessage,
		ColumnNameRequestsUserId,
		ColumnNameRequestsCreatedAt,
		ColumnNameRequestsUpdatedAt,
	}
}
