// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_requests

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Request, error)
	Delete(ctx context.Context, id string) error
	GetByID(ctx context.Context, id string) (*models.Request, error)
	GetPendingRequests(ctx context.Context) ([]*models.Request, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
