// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests_gen.sql

package repo_requests

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
)

const create = `-- name: Create :one
INSERT INTO requests (id, data, status, error_message, user_id)
	VALUES (?, ?, ?, ?, ?)
	RETURNING id, data, status, error_message, user_id, created_at, updated_at
`

type CreateParams struct {
	ID           int64                    `db:"id" json:"id" validate:"required"`
	Data         string                   `db:"data" json:"data" validate:"required"`
	Status       models.RequestStatusType `db:"status" json:"status" validate:"required,oneof=pending completed failed"`
	ErrorMessage *string                  `db:"error_message" json:"error_message"`
	UserID       string                   `db:"user_id" json:"user_id" validate:"required"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Request, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Data,
		arg.Status,
		arg.ErrorMessage,
		arg.UserID,
	)
	var i models.Request
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.Status,
		&i.ErrorMessage,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM requests WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, data, status, error_message, user_id, created_at, updated_at FROM requests WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (*models.Request, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Request
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.Status,
		&i.ErrorMessage,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
