// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request.sql

package repo_requests

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
)

const updateStatus = `-- name: UpdateStatus :exec
UPDATE todos
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, title, description, status, planned_date, completed_at, request_id, created_at, updated_at
`

func (q *Queries) UpdateStatus(ctx context.Context, status models.TodoStatusType, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateStatus, status, iD)
	return err
}
