// Code generated by pgxgen. DO NOT EDIT.
package repo_notes

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameNotes TableName = "notes"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameNotesId          ColumnName = "id"
	ColumnNameNotesUserId      ColumnName = "user_id"
	ColumnNameNotesTitle       ColumnName = "title"
	ColumnNameNotesBody        ColumnName = "body"
	ColumnNameNotesCreatedAt   ColumnName = "created_at"
	ColumnNameNotesUpdatedAt   ColumnName = "updated_at"
	ColumnNameNotesWorkspaceId ColumnName = "workspace_id"
)

func NotesColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameNotesId,
		ColumnNameNotesUserId,
		ColumnNameNotesTitle,
		ColumnNameNotesBody,
		ColumnNameNotesCreatedAt,
		ColumnNameNotesUpdatedAt,
		ColumnNameNotesWorkspaceId,
	}
}
