// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes_gen.sql

package repo_notes

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
)

const create = `-- name: Create :one
INSERT INTO notes (id, user_id, title, body)
	VALUES (?, ?, ?, ?)
	RETURNING id, user_id, title, body, created_at, updated_at
`

type CreateParams struct {
	ID     string `db:"id" json:"id" validate:"required"`
	UserID int64  `db:"user_id" json:"user_id" validate:"required"`
	Title  string `db:"title" json:"title" validate:"required"`
	Body   string `db:"body" json:"body"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Note, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Body,
	)
	var i models.Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM notes WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, user_id, title, body, created_at, updated_at FROM notes WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Note, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
