// Code generated by pgxgen. DO NOT EDIT.
package repo_tags

import (
	"github.com/gobeam/stringy"
	"strings"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameTags TableName = "tags"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameTagsId        ColumnName = "id"
	ColumnNameTagsUserId    ColumnName = "user_id"
	ColumnNameTagsName      ColumnName = "name"
	ColumnNameTagsColor     ColumnName = "color"
	ColumnNameTagsCreatedAt ColumnName = "created_at"
	ColumnNameTagsUpdatedAt ColumnName = "updated_at"
)

func TagsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameTagsId,
		ColumnNameTagsUserId,
		ColumnNameTagsName,
		ColumnNameTagsColor,
		ColumnNameTagsCreatedAt,
		ColumnNameTagsUpdatedAt,
	}
}
