// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags_gen.sql

package repo_tags

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
)

const create = `-- name: Create :one
INSERT INTO tags (id, user_id, name, color)
	VALUES (?, ?, ?, ?)
	RETURNING id, user_id, name, color, created_at, updated_at
`

type CreateParams struct {
	ID     string `db:"id" json:"id" validate:"required"`
	UserID int64  `db:"user_id" json:"user_id" validate:"required"`
	Name   string `db:"name" json:"name" validate:"required"`
	Color  string `db:"color" json:"color"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Tag, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
	)
	var i models.Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM tags WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, user_id, name, color, created_at, updated_at FROM tags WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Tag, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
