// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.13
package repo_inbox

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameInbox TableName = "inbox"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameInboxId             ColumnName = "id"
	ColumnNameInboxData           ColumnName = "data"
	ColumnNameInboxAdditionalData ColumnName = "additional_data"
	ColumnNameInboxUserId         ColumnName = "user_id"
	ColumnNameInboxCreatedAt      ColumnName = "created_at"
	ColumnNameInboxUpdatedAt      ColumnName = "updated_at"
)

func InboxColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameInboxId,
		ColumnNameInboxData,
		ColumnNameInboxAdditionalData,
		ColumnNameInboxUserId,
		ColumnNameInboxCreatedAt,
		ColumnNameInboxUpdatedAt,
	}
}
