// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_gen.sql

package repo_inbox

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
	"github.com/sxwebdev/donejournal/internal/store/storecmn"
)

const create = `-- name: Create :one
INSERT INTO inbox (id, data, additional_data, user_id)
	VALUES (?, ?, ?, ?)
	RETURNING id, data, additional_data, user_id, created_at, updated_at
`

type CreateParams struct {
	ID             string             `db:"id" json:"id" validate:"required"`
	Data           string             `db:"data" json:"data" validate:"required"`
	AdditionalData storecmn.JSONField `db:"additional_data" json:"additional_data"`
	UserID         string             `db:"user_id" json:"user_id" validate:"required"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Inbox, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Data,
		arg.AdditionalData,
		arg.UserID,
	)
	var i models.Inbox
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.AdditionalData,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM inbox WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, data, additional_data, user_id, created_at, updated_at FROM inbox WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Inbox, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Inbox
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.AdditionalData,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
