// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.13
package repo_todos

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameTodos TableName = "todos"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameTodosId          ColumnName = "id"
	ColumnNameTodosUserId      ColumnName = "user_id"
	ColumnNameTodosTitle       ColumnName = "title"
	ColumnNameTodosDescription ColumnName = "description"
	ColumnNameTodosStatus      ColumnName = "status"
	ColumnNameTodosPlannedDate ColumnName = "planned_date"
	ColumnNameTodosCompletedAt ColumnName = "completed_at"
	ColumnNameTodosRequestId   ColumnName = "request_id"
	ColumnNameTodosCreatedAt   ColumnName = "created_at"
	ColumnNameTodosUpdatedAt   ColumnName = "updated_at"
)

func TodosColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameTodosId,
		ColumnNameTodosUserId,
		ColumnNameTodosTitle,
		ColumnNameTodosDescription,
		ColumnNameTodosStatus,
		ColumnNameTodosPlannedDate,
		ColumnNameTodosCompletedAt,
		ColumnNameTodosRequestId,
		ColumnNameTodosCreatedAt,
		ColumnNameTodosUpdatedAt,
	}
}
