// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_todos

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Todo, error)
	Delete(ctx context.Context, id string) error
	GetByID(ctx context.Context, id string) (*models.Todo, error)
	UpdateStatus(ctx context.Context, status models.TodoStatusType, iD string) error
}

var _ Querier = (*Queries)(nil)
