// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.14
package repo_workspaces

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameWorkspaces TableName = "workspaces"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameWorkspacesId          ColumnName = "id"
	ColumnNameWorkspacesUserId      ColumnName = "user_id"
	ColumnNameWorkspacesName        ColumnName = "name"
	ColumnNameWorkspacesDescription ColumnName = "description"
	ColumnNameWorkspacesArchived    ColumnName = "archived"
	ColumnNameWorkspacesCreatedAt   ColumnName = "created_at"
	ColumnNameWorkspacesUpdatedAt   ColumnName = "updated_at"
)

func WorkspacesColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameWorkspacesId,
		ColumnNameWorkspacesUserId,
		ColumnNameWorkspacesName,
		ColumnNameWorkspacesDescription,
		ColumnNameWorkspacesArchived,
		ColumnNameWorkspacesCreatedAt,
		ColumnNameWorkspacesUpdatedAt,
	}
}
