// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces_gen.sql

package repo_workspaces

import (
	"context"

	"github.com/sxwebdev/donejournal/internal/models"
)

const create = `-- name: Create :one
INSERT INTO workspaces (id, user_id, name, description, archived)
	VALUES (?, ?, ?, ?, ?)
	RETURNING id, user_id, name, description, archived, created_at, updated_at
`

type CreateParams struct {
	ID          string `db:"id" json:"id" validate:"required"`
	UserID      int64  `db:"user_id" json:"user_id" validate:"required"`
	Name        string `db:"name" json:"name" validate:"required"`
	Description string `db:"description" json:"description"`
	Archived    bool   `db:"archived" json:"archived"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.Workspace, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Archived,
	)
	var i models.Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const delete = `-- name: Delete :exec
DELETE FROM workspaces WHERE id=?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, user_id, name, description, archived, created_at, updated_at FROM workspaces WHERE id=? LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id string) (*models.Workspace, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i models.Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
